import { articleSalary30Man } from './salary-30man.js';
import { articleLostZairyu } from './lost-zairyu.js';

export const ALL_ARTICLES = [
  articleSalary30Man,
  articleLostZairyu,
  {
    id: 'thue-nha-hop-dong',
    slug: 'hop-dong-thue-nha-nhat-ban',
    title: 'Hợp đồng thuê nhà ở Nhật: Những khoản tiền không lấy lại được',
    excerpt: 'Tiền lễ (reikin), tiền cọc (shikikin), phí đổi chìa khóa và bảo hiểm hỏa hoạn: khoản nào bắt buộc và khoản nào có thể thương lượng.',
    category: 'life',
    tags: ['Thuê nhà', 'Hợp đồng', 'Rác & Vứt đồ'],
    publishedAt: '2026-09-08',
    updatedAt: '2026-09-15',
    readingTime: 7,
    status: 'review',
    coverImage: '/images/hero-everyday-japan.jpg',
    socialImage: '/images/og/og-default.png',
    author: { name: 'Ban Biên Tập Chotto', role: 'Nội dung đời sống & nhà ở' },
    sections: [
      {
        type: 'intro',
        content: 'Thuê nhà tại Nhật Bản là một trong những thủ tục phổ biến nhất đối với người nước ngoài. Bên cạnh tiền thuê nhà hàng tháng, chi phí ban đầu (Shoki Hiyo) thường gấp 3 đến 5 lần tiền nhà.',
      },
      {
        type: 'heading',
        level: 2,
        text: '1. Phân biệt các khoản tiền đầu vào khi ký hợp đồng',
      },
      {
        type: 'list',
        items: [
          'Tiền lễ (礼金 - Reikin): Tiền biếu chủ nhà để cảm ơn, hoàn toàn không được hoàn trả.',
          'Tiền cọc (敷金 - Shikikin): Tiền thế chân bảo đảm, sau khi trừ tiền dọn dẹp vệ sinh khi trả nhà sẽ được hoàn lại phần dư.',
          'Phí công ty bảo lãnh (Hoshonin-gaisha): Thường áp dụng với hầu hết người nước ngoài không có người Nhật bảo lãnh.',
          'Bảo hiểm hỏa hoạn (Kasai Hoken): Bắt buộc duy trì trong suốt thời hạn thuê nhà.',
        ],
      },
      {
        type: 'term',
        term: '敷金（しききん） và 礼金（れいきん）',
        reading: 'Shikikin & Reikin',
        meaning: 'Tiền đặt cọc (có thể hoàn trả một phần) và Tiền lễ (không hoàn lại).',
      },
      {
        type: 'note',
        title: 'Mẹo tìm hiểu hợp đồng',
        content: 'Bạn có thể trao đổi với công ty bất động sản để tìm các căn hộ "Zero-Zero" (0 tiền cọc, 0 tiền lễ) hoặc tìm hiểu các ưu đãi miễn phí tháng đầu tiên (Free Rent) vào mùa thấp điểm.',
      },
    ],
    relatedArticleIds: [
      'doi-bang-lai-xe-viet-nhat',
      'luong-30-man-thuc-nhan-bao-nhieu',
    ],
    relatedToolIds: ['moving-cost-jp', 'address-change-checklist-jp'],
    seo: {
      metaTitle: 'Hợp đồng thuê nhà ở Nhật: Các khoản phí ban đầu | Chotto',
      metaDescription: 'Giải thích chi tiết tiền lễ, tiền cọc, phí bảo lãnh khi thuê nhà tại Nhật Bản và kinh nghiệm thương lượng chi phí đầu vào.',
      canonical: 'https://chottoday.com/articles/hop-dong-thue-nha-nhat-ban',
      structuredDataType: 'Article',
    },
  },
  {
    id: 'doi-bang-lai',
    slug: 'doi-bang-lai-xe-viet-nhat',
    title: 'Đổi bằng lái xe Việt Nam sang bằng Nhật Bản (Gaimen Kirikae)',
    excerpt: 'Điều kiện 3 tháng lái xe tại Việt Nam, thủ tục dịch thuật bằng tại JAF và quy trình thi lý thuyết 10 câu bằng tiếng Việt.',
    category: 'life',
    tags: ['Bằng lái xe', 'Hành chính', 'Đời sống'],
    publishedAt: '2026-09-05',
    updatedAt: '2026-09-14',
    readingTime: 6,
    status: 'review',
    coverImage: '/images/hero-everyday-japan.jpg',
    socialImage: '/images/og/og-default.png',
    author: { name: 'Ban Biên Tập Chotto', role: 'Nội dung thủ tục đời sống' },
    sections: [
      {
        type: 'intro',
        content: 'Thủ tục Gaimen Kirikae (外免切替) cho phép người có bằng lái xe ô tô tại Việt Nam chuyển đổi sang bằng lái xe Nhật Bản theo quy trình rút gọn nếu đáp ứng đủ các điều kiện theo quy định.',
      },
      {
        type: 'heading',
        level: 2,
        text: '1. Điều kiện tiên quyết để được đổi bằng',
      },
      {
        type: 'warning',
        title: 'Quy tắc 3 tháng lưu trú tại Việt Nam sau ngày cấp bằng',
        content: 'Bạn cần chứng minh đã ở Việt Nam tổng cộng ít nhất 90 ngày sau ngày bằng lái có hiệu lực. Giấy tờ chứng minh thường là dấu xuất nhập cảnh trên hộ chiếu hoặc giấy chứng nhận di trú.',
      },
      {
        type: 'steps',
        items: [
          { stepNumber: 1, title: 'Dịch thuật bằng lái xe tại JAF', text: 'Gửi bản sao bằng lái xe đến Liên đoàn Ô tô Nhật Bản (JAF) để lấy bản dịch thuật công chứng tiếng Nhật theo quy định.' },
          { stepNumber: 2, title: 'Chuẩn bị ảnh thẻ và hồ sơ', text: 'Chụp ảnh thẻ cỡ 3cm x 2.4cm đáp ứng quy chuẩn hồ sơ thi bằng lái xe tại Nhật.' },
          { stepNumber: 3, title: 'Thi lý thuyết 10 câu', text: 'Tại nhiều trung tâm, bạn có thể chọn thi bằng tiếng Việt, trả lời đúng 7/10 câu để hoàn thành phần kiểm tra lý thuyết trước khi sang bài thi thực hành.' },
        ],
      },
      {
        type: 'toolCTA',
        toolId: 'id-photo-studio',
        icon: '📸',
        editorial: {
          title: 'Chuẩn bị ảnh thẻ đổi bằng lái xe tiện lợi',
          description: 'Tạo file ảnh thẻ đúng chuẩn nộp trung tâm sát hạch lái xe Menkyo Center.',
        },
        ctaText: 'Tạo ảnh thẻ ngay',
        note: 'Hỗ trợ xuất file in tại các hệ thống combini',
        badge: 'Mở trong Toolio',
      },
    ],
    relatedArticleIds: [
      'hop-dong-thue-nha-nhat-ban',
    ],
    relatedToolIds: ['id-photo-studio'],
    seo: {
      metaTitle: 'Đổi bằng lái xe Việt Nam sang Nhật (Gaimen Kirikae) | Chotto',
      metaDescription: 'Hướng dẫn quy trình đổi bằng lái xe Việt sang Nhật: điều kiện 90 ngày, dịch thuật JAF, thi lý thuyết tiếng Việt tại Menkyo Center.',
      canonical: 'https://chottoday.com/articles/doi-bang-lai-xe-viet-nhat',
      structuredDataType: 'Article',
    },
  },
  {
    id: 'gia-han-visa-3-thang',
    slug: 'gia-han-visa-ky-su-truoc-3-thang',
    title: 'Gia hạn visa kỹ sư trước 3 tháng: Thủ tục và giấy tờ công ty cần cấp',
    excerpt: 'Cục xuất nhập cảnh cho phép nộp đơn gia hạn trước ngày hết hạn 3 tháng. Danh mục giấy tờ tham khảo cần chuẩn bị từ cá nhân và bộ phận nhân sự.',
    category: 'doc',
    tags: ['Visa & Nyukan', 'Thẻ cư trú', 'Hành chính'],
    publishedAt: '2026-09-02',
    updatedAt: '2026-09-14',
    readingTime: 6,
    status: 'review',
    coverImage: '/images/hero-everyday-japan.jpg',
    socialImage: '/images/og/og-default.png',
    author: { name: 'Ban Biên Tập Chotto', role: 'Nội dung thủ tục visa' },
    sections: [
      {
        type: 'intro',
        content: 'Người lao động có thể nộp đơn xin gia hạn thời hạn lưu trú tại Cục Quản lý Xuất nhập cảnh (Nyukan) trước ngày hết hạn visa tối đa 3 tháng.',
      },
      {
        type: 'heading',
        level: 2,
        text: '1. Danh mục giấy tờ tham khảo cần nộp',
      },
      {
        type: 'list',
        items: [
          'Đơn xin gia hạn tư cách lưu trú (theo mẫu tư cách làm việc tương ứng).',
          'Ảnh thẻ 3cm × 4cm chụp trong vòng 3 tháng gần nhất.',
          'Hộ chiếu và thẻ cư trú Zairyu bản gốc.',
          'Giấy chứng nhận đang làm việc (Zaishoku Shomeisho) do công ty cấp.',
          'Giấy chứng nhận nộp thuế và thuế thị dân (Nozei Shomeisho & Kazei Shomeisho) xin tại Shiyakusho.',
        ],
      },
    ],
    relatedArticleIds: [
      'mat-the-zairyu-thi-lam-gi',
    ],
    relatedToolIds: ['id-photo-studio', 'residence-renewal-guide-jp'],
    seo: {
      metaTitle: 'Gia hạn visa kỹ sư trước 3 tháng: Giấy tờ cần chuẩn bị | Chotto',
      metaDescription: 'Danh mục hồ sơ gia hạn visa kỹ sư nộp Nyukan: giấy tờ cá nhân, giấy tờ công ty cần cấp và thời hạn thụ lý hồ sơ.',
      canonical: 'https://chottoday.com/articles/gia-han-visa-ky-su-truoc-3-thang',
      structuredDataType: 'Article',
    },
  },
  {
    id: 'khai-thue-cuoi-nam',
    slug: 'khai-thue-cuoi-nam-gui-tien-ve-nha',
    title: 'Hướng dẫn khai thuế cuối năm (Nenmatsu Chosei) cho người gửi tiền về nhà',
    excerpt: 'Quy định về chứng minh chuyển tiền cho người phụ thuộc ở nước ngoài và những điểm cần lưu ý khi nộp giấy tờ cho doanh nghiệp.',
    category: 'work',
    tags: ['Khai thuế', 'Thuế thu nhập', 'Chuyển tiền', 'Lương thực nhận'],
    publishedAt: '2026-08-28',
    updatedAt: '2026-09-12',
    readingTime: 5,
    status: 'review',
    coverImage: '/images/hero-everyday-japan.jpg',
    socialImage: '/images/og/og-default.png',
    author: { name: 'Ban Biên Tập Chotto', role: 'Nội dung thuế & an sinh' },
    sections: [
      {
        type: 'intro',
        content: 'Vào khoảng tháng 11 hàng năm, các doanh nghiệp tại Nhật Bản thường tiến hành thủ tục điều chỉnh thuế cuối năm (Nenmatsu Chosei) để cân đối số thuế thu nhập đã tạm khấu trừ trong năm của người lao động.',
      },
      {
        type: 'warning',
        title: 'Lưu ý về chứng từ chuyển tiền cho người phụ thuộc',
        content: 'Theo quy định hiện hành đối với người phụ thuộc từ 30 đến 69 tuổi sinh sống ở nước ngoài, người nộp thuế cần cung cấp chứng từ chuyển tiền hợp lệ đứng tên người phụ thuộc đáp ứng các tiêu chuẩn quy định của cơ quan thuế.',
      },
      {
        type: 'toolCTA',
        toolId: 'japan-tax-simulator',
        icon: '🧮',
        editorial: {
          title: 'Mô phỏng tiền hoàn thuế khi khai người phụ thuộc',
          description: 'Xem ước tính số tiền điều chỉnh thuế thu nhập và thuế thị dân tham khảo.',
        },
        ctaText: 'Tính thử hoàn thuế',
        note: 'Công cụ mô phỏng độc lập trên Toolio',
        badge: 'Mở trong Toolio',
      },
    ],
    relatedArticleIds: [
      'luong-30-man-thuc-nhan-bao-nhieu',
    ],
    relatedToolIds: ['japan-tax-simulator'],
    seo: {
      metaTitle: 'Hướng dẫn khai thuế cuối năm Nenmatsu Chosei | Chotto',
      metaDescription: 'Cách điền giấy khai thuế cuối năm tại Nhật Bản, điều kiện gửi tiền phụ dưỡng người thân ở Việt Nam để được giảm trừ thuế.',
      canonical: 'https://chottoday.com/articles/khai-thue-cuoi-nam-gui-tien-ve-nha',
      structuredDataType: 'Article',
    },
  },
  {
    id: 'giam-phi-bhyt',
    slug: 'bao-hiem-y-te-quoc-dan-giam-phi',
    title: 'Bảo hiểm y tế quốc dân (Kokumin Kenko Hoken) giảm phí khi thu nhập thấp',
    excerpt: 'Nếu bạn vừa thôi việc hoặc đang là du học sinh, bạn có thể tìm hiểu thủ tục xin giảm mức đóng tại văn phòng Shiyakusho.',
    category: 'health',
    tags: ['Bảo hiểm y tế', 'Khám bệnh', 'Shiyakusho'],
    publishedAt: '2026-08-20',
    updatedAt: '2026-09-13',
    readingTime: 4,
    status: 'review',
    coverImage: '/images/hero-everyday-japan.jpg',
    socialImage: '/images/og/og-default.png',
    author: { name: 'Ban Biên Tập Chotto', role: 'Nội dung an sinh y tế' },
    sections: [
      {
        type: 'intro',
        content: 'Bảo hiểm Y tế Quốc dân (Kokumin Kenko Hoken) thường được tính dựa trên mức thu nhập của năm trước đó. Trường hợp thu nhập sụt giảm đáng kể hoặc gián đoạn, người tham gia có thể tìm hiểu chế độ miễn giảm theo quy định của địa phương.',
      },
      {
        type: 'note',
        title: 'Các khung giảm trừ tham khảo',
        content: 'Tùy thuộc vào quy định cụ thể của từng địa phương và mức thu nhập thực tế, người tham gia bảo hiểm có thể được xem xét các mức miễn giảm tương ứng.',
      },
    ],
    relatedArticleIds: [
      'di-kham-benh-tu-vung-trieu-chung',
    ],
    relatedToolIds: ['social-insurance-jp'],
    seo: {
      metaTitle: 'Xin miễn giảm Bảo hiểm y tế quốc dân tại Nhật | Chotto',
      metaDescription: 'Thủ tục xin giảm mức đóng bảo hiểm Kokumin Kenko Hoken tại Shiyakusho cho người thôi việc, thu nhập thấp hoặc du học sinh.',
      canonical: 'https://chottoday.com/articles/bao-hiem-y-te-quoc-dan-giam-phi',
      structuredDataType: 'Article',
    },
  },
  {
    id: 'tu-vung-kham-benh',
    slug: 'di-kham-benh-tu-vung-trieu-chung',
    title: 'Bảng từ vựng triệu chứng cơ thể khi đi khám bệnh tại Nhật',
    excerpt: 'Tổng hợp từ vựng và mẫu câu giao tiếp tham khảo để mô tả tình trạng đau đầu, đau bụng, sốt và dị ứng khi gặp bác sĩ.',
    category: 'health',
    tags: ['Từ vựng y tế', 'Khám bệnh', 'Cấp cứu'],
    publishedAt: '2026-08-15',
    updatedAt: '2026-09-10',
    readingTime: 5,
    status: 'review',
    coverImage: '/images/hero-everyday-japan.jpg',
    socialImage: '/images/og/og-default.png',
    author: { name: 'Ban Biên Tập Chotto', role: 'Nội dung y tế thường thức' },
    sections: [
      {
        type: 'intro',
        content: 'Khi đi khám tại phòng khám hoặc bệnh viện ở Nhật Bản, việc mô tả đúng vị trí và cảm giác triệu chứng giúp bác sĩ nắm bắt tình trạng ban đầu dễ dàng hơn.',
      },
      {
        type: 'term',
        term: '問診票（もんしんひょう）',
        reading: 'Monshinhō',
        meaning: 'Phiếu khai báo triệu chứng ban đầu cần điền khi đến cơ sở y tế Nhật Bản.',
      },
      {
        type: 'list',
        items: [
          'Đau nhức đầu: 頭がズキズキ痛む (Atama ga zukizuki itamu)',
          'Đau quặn bụng: お腹がキリキリ痛む (Onaka ga kirikiri itamu)',
          'Sốt cao: 高熱が出る (Kōnetsu ga deru)',
          'Buồn nôn: 吐き気がする (Hakike ga suru)',
        ],
      },
    ],
    relatedArticleIds: [
      'bao-hiem-y-te-quoc-dan-giam-phi',
    ],
    relatedToolIds: [],
    seo: {
      metaTitle: 'Từ vựng tiếng Nhật mô tả triệu chứng khi đi khám bệnh | Chotto',
      metaDescription: 'Tổng hợp mẫu câu và từ vựng tiếng Nhật điền phiếu Monshinhyo, mô tả triệu chứng đau ốm khi đến bệnh viện ở Nhật.',
      canonical: 'https://chottoday.com/articles/di-kham-benh-tu-vung-trieu-chung',
      structuredDataType: 'Article',
    },
  },
  {
    id: 'mau-cau-shiyakusho',
    slug: 'mau-cau-tieng-nhat-shiyakusho-buu-dien',
    title: 'Mẫu câu tiếng Nhật thường gặp khi gọi điện lên Shiyakusho và bưu điện',
    excerpt: 'Tổng hợp các mẫu câu giao tiếp cơ bản để hỏi tình trạng hồ sơ giấy tờ và hẹn giờ giao lại bưu phẩm.',
    category: 'study',
    tags: ['Mẫu câu Shiyakusho', 'Từ vựng hành chính', 'Tiếng Nhật'],
    publishedAt: '2026-08-10',
    updatedAt: '2026-09-11',
    readingTime: 5,
    status: 'review',
    coverImage: '/images/hero-everyday-japan.jpg',
    socialImage: '/images/og/og-default.png',
    author: { name: 'Ban Biên Tập Chotto', role: 'Nội dung tiếng Nhật hành chính' },
    sections: [
      {
        type: 'intro',
        content: 'Trao đổi qua điện thoại tại cơ quan hành chính đòi hỏi cách diễn đạt lịch sự và rõ ràng. Nắm vững các câu chào và cách diễn đạt chuẩn mực giúp cuộc gọi diễn ra thuận lợi.',
      },
      {
        type: 'steps',
        items: [
          { stepNumber: 1, title: 'Mở đầu cuộc gọi', text: 'お忙しいところ恐れ入ります。ベトナム人の[Tên bạn]と申します。(Xin lỗi vì làm phiền lúc bận, tôi là [Tên bạn] người Việt Nam).' },
          { stepNumber: 2, title: 'Nêu lý do gọi', text: '住民票の件でお伺いしたいのですが。(Tôi muốn hỏi về việc giấy xác nhận cư trú Juminhyo).' },
          { stepNumber: 3, title: 'Nhờ nhắc lại khi chưa nghe rõ', text: '恐れ入りますが、もう一度ゆっくりお願いできますでしょうか。(Xin lỗi, có thể nhắc lại chậm một chút được không ạ?).' },
        ],
      },
    ],
    relatedArticleIds: [
      'mat-the-zairyu-thi-lam-gi',
    ],
    relatedToolIds: ['administrative-navigator-jp'],
    seo: {
      metaTitle: 'Mẫu câu tiếng Nhật gọi điện Shiyakusho & Bưu điện | Chotto',
      metaDescription: 'Mẫu câu tiếng Nhật lịch sự khi gọi điện thoại lên Shiyakusho hỏi giấy tờ hoặc bưu điện xin giao lại bưu phẩm vắng nhà.',
      canonical: 'https://chottoday.com/articles/mau-cau-tieng-nhat-shiyakusho-buu-dien',
      structuredDataType: 'Article',
    },
  },
  {
    id: 'hoa-don-invoice-freelance',
    slug: 'hoa-don-invoice-tekikaku-freelance',
    title: 'Quy chuẩn hóa đơn Invoice (Tekikaku Seikyusho) cho người làm tự do',
    excerpt: 'Tìm hiểu cách thể hiện mã số doanh nghiệp, các mức thuế suất trên chứng từ thanh toán theo luật thuế Invoice tại Nhật.',
    category: 'tool',
    tags: ['Hóa đơn', 'Khai thuế', 'Công cụ Chotto'],
    publishedAt: '2026-08-05',
    updatedAt: '2026-09-09',
    readingTime: 4,
    status: 'review',
    coverImage: '/images/hero-everyday-japan.jpg',
    socialImage: '/images/og/og-default.png',
    author: { name: 'Ban Biên Tập Chotto', role: 'Nội dung công cụ kế toán' },
    sections: [
      {
        type: 'intro',
        content: 'Chế độ hóa đơn hợp lệ (Invoice Seido) áp dụng tại Nhật Bản quy định các tiêu chí cần có trên hóa đơn thanh toán để bên mua hàng hoặc đối tác được khấu trừ thuế đầu vào.',
      },
      {
        type: 'toolCTA',
        toolId: 'invoice-studio',
        icon: '🧾',
        editorial: {
          title: 'Tạo hóa đơn Invoice hợp lệ Nhật Bản',
          description: 'Biểu mẫu lập hóa đơn hỗ trợ tính các mức thuế suất theo quy chuẩn NTA, sẵn sàng xuất file in hoặc gửi cho đối tác.',
        },
        ctaText: 'Tạo hóa đơn ngay',
        note: 'Mẫu theo quy định của Cục Thuế Quốc Gia Nhật Bản',
        badge: 'Mở trong Toolio',
      },
    ],
    relatedArticleIds: [
      'luong-30-man-thuc-nhan-bao-nhieu',
    ],
    relatedToolIds: ['invoice-studio'],
    seo: {
      metaTitle: 'Quy chuẩn hóa đơn Invoice (Tekikaku Seikyusho) Nhật Bản | Chotto',
      metaDescription: 'Quy định các tiêu chí bắt buộc trên hóa đơn Invoice Nhật Bản: mã số T-number, tách thuế suất 8% và 10% theo luật NTA.',
      canonical: 'https://chottoday.com/articles/hoa-don-invoice-tekikaku-freelance',
      structuredDataType: 'Article',
    },
  },
];
