/**
 * Japanese & Vietnamese Terminology Index for Intelligent Discovery
 * 
 * Maps natural everyday user language, official Japanese kanji,
 * Romaji transcriptions, common typos, and conceptual categories.
 */

export const TERMINOLOGY_CONCEPTS = [
  {
    id: 'residence-card',
    name: 'Thẻ cư trú (在留カード)',
    category: 'doc',
    japanese: ['在留カード', '在留資格', '外国人登録'],
    romaji: ['zairyu', 'zairyu card', 'zairyuu', 'zairyuu kaado', 'gaikokujin'],
    vietnamese: [
      'thẻ cư trú',
      'the cu tru',
      'thẻ zairyu',
      'the zairyu',
      'thẻ ngoại kiều',
      'the ngoai kieu',
      'mất thẻ',
      'mat the',
      'mất zairyu',
      'làm lại thẻ',
      'cấp lại thẻ',
      'đánh rơi thẻ',
    ],
    typos: ['zairu', 'zaryu', 'zairy', 'the cu tru bi mat', 'zairu bi mat'],
    primaryArticleSlug: 'mat-the-zairyu-thi-lam-gi',
    primaryProblemId: 'prob-newcomer',
    primaryToolId: 'id-photo-studio',
  },
  {
    id: 'income-tax',
    name: 'Thuế thu nhập (所得税)',
    category: 'work',
    japanese: ['所得税', '源泉徴収', '手取り', '額面'],
    romaji: ['shotokuzei', 'gensen choshu', 'tedori', 'gakumen'],
    vietnamese: [
      'thuế thu nhập',
      'thue thu nhap',
      'thuế cá nhân',
      'khấu trừ thuế',
      'lương 30 man',
      'luong 30 man',
      'lương thực nhận',
      'luong thuc nhan',
      'bị trừ lương',
      'lương bị trừ nhiều',
      'tiền về tay',
      'bảng lương',
      'bang luong',
    ],
    typos: ['luong 30man', 'luong bi tru', 'thuc nhan', 'tedori la gi'],
    primaryArticleSlug: 'luong-30-man-thuc-nhan-bao-nhieu',
    primaryProblemId: 'prob-tax',
    primaryToolId: 'japan-tax-simulator',
  },
  {
    id: 'resident-tax',
    name: 'Thuế thị dân (住民税)',
    category: 'work',
    japanese: ['住民税', '市民税', '特別徴収', '普通徴収'],
    romaji: ['juminzei', 'shiminzei', 'tokubetsu choshu', 'futsu choshu'],
    vietnamese: [
      'thuế thị dân',
      'thue thi dan',
      'thuế cư trú',
      'thue cu tru',
      'thuế thành phố',
      'giấy thuế màu xanh',
      'giấy xanh lá',
      'năm thứ 2 bị trừ thuế',
      'tại sao bị trừ thuế thị dân',
    ],
    typos: ['juminze', 'thue thi dan', 'giay xanh', 'juminzei la gi'],
    primaryArticleSlug: 'luong-30-man-thuc-nhan-bao-nhieu',
    primaryProblemId: 'prob-unknown-mail',
    primaryToolId: 'japan-tax-simulator',
  },
  {
    id: 'pension',
    name: 'Bảo hiểm Nenkin / Lương hưu (年金)',
    category: 'work',
    japanese: ['厚生年金', '国民年金', '脱退一時金', '年金手帳'],
    romaji: ['nenkin', 'kosei nenkin', 'kokumin nenkin', 'dattai ichijikin'],
    vietnamese: [
      'nenkin',
      'tiền nenkin',
      'lương hưu',
      'luong huu',
      'rút nenkin',
      'rut nenkin',
      'lấy lại tiền nenkin',
      'tiền một lần',
      'lump sum',
      'tự đóng nenkin',
      'sổ nenkin',
    ],
    typos: ['nenkinn', 'nenkin la gi', 'rut tien nenkin', 'koseinenkin'],
    primaryArticleSlug: 'luong-30-man-thuc-nhan-bao-nhieu',
    primaryProblemId: 'prob-tax',
    primaryToolId: 'social-insurance-jp',
  },
  {
    id: 'health-insurance',
    name: 'Bảo hiểm y tế (健康保険 / 社会保険)',
    category: 'health',
    japanese: ['健康保険', '社会保険', '国民健康保険', '保険証'],
    romaji: ['shakai hoken', 'kenko hoken', 'kokumin kenko hoken', 'hokensho'],
    vietnamese: [
      'bảo hiểm y tế',
      'bao hiem y te',
      'bảo hiểm xã hội',
      'bao hiem xa hoi',
      'shakai hoken',
      'thẻ bảo hiểm',
      'giảm phí bảo hiểm',
      'miễn giảm bảo hiểm',
      'bảo hiểm quốc dân',
    ],
    typos: ['shakaihoken', 'bhyt nhat', 'the bao hiem', 'giam phi bao hiem'],
    primaryArticleSlug: 'bao-hiem-y-te-quoc-dan-giam-phi',
    primaryProblemId: 'prob-job-change',
    primaryToolId: 'social-insurance-jp',
  },
  {
    id: 'driving-license',
    name: 'Đổi bằng lái xe (外免切替)',
    category: 'life',
    japanese: ['運転免許', '外免切替', '運転免許センター', 'JAF翻訳'],
    romaji: ['gaimen kirikae', 'menkyo', 'menkyo sentaa', 'jaf honyaku'],
    vietnamese: [
      'đổi bằng lái',
      'doi bang lai',
      'bằng lái xe',
      'bang lai xe',
      'bằng lái ô tô',
      'thi lý thuyết bằng lái',
      'dịch bằng jaf',
      'gaimen kirikae',
      '90 ngày ở việt nam',
      'lái xe ở nhật',
    ],
    typos: ['doi bang lai xe', 'menkyo viet nam', 'gaimen', 'thi bang lai'],
    primaryArticleSlug: 'doi-bang-lai-xe-viet-nhat',
    primaryProblemId: 'prob-driving',
    primaryToolId: 'id-photo-studio',
  },
  {
    id: 'rent-housing',
    name: 'Thuê nhà & Hợp đồng (賃貸 / 敷金・礼金)',
    category: 'life',
    japanese: ['賃貸', '敷金', '礼金', '火災保険', '更新料'],
    romaji: ['chintai', 'shikikin', 'reikin', 'kasai hoken', 'koushinryou'],
    vietnamese: [
      'thuê nhà',
      'thue nha',
      'chuyển nhà',
      'chuyen nha',
      'hợp đồng thuê nhà',
      'tiền cọc',
      'tien coc',
      'tiền lễ',
      'tien le',
      'chi phí ban đầu',
      'shikikin',
      'reikin',
      'trả nhà',
      'vứt rác',
      'đổi địa chỉ',
      'doi dia chi',
      'chuyển địa chỉ',
      'chuyen dia chi',
      'đăng ký địa chỉ',
      'dang ky dia chi',
    ],
    typos: ['thue nha o nhat', 'tien shikikin', 'reikin la gi', 'chuyen nha', 'doi dia chi'],
    primaryArticleSlug: 'hop-dong-thue-nha-nhat-ban',
    primaryProblemId: 'prob-moving',
    primaryToolId: 'moving-admin-checker-jp',
  },
  {
    id: 'job-change',
    name: 'Nghỉ việc & Chuyển việc (退職 / 転職)',
    category: 'work',
    japanese: ['退職', '転職', '雇用保険', '離職票', 'ハローワーク'],
    romaji: ['taishoku', 'tenshoku', 'koyou hoken', 'rishokuhyou', 'hello work'],
    vietnamese: [
      'nghỉ việc',
      'nghi viec',
      'chuyển việc',
      'chuyen viec',
      'thôi việc',
      'chuyển công ty',
      'thất nghiệp',
      'trợ cấp thất nghiệp',
      'bảo hiểm thất nghiệp',
      'báo nyukan nghỉ việc',
      'giấy rishokuhyo',
    ],
    typos: ['nghi viec o nhat', 'chuyen cong ty', 'tro cap that nghiep'],
    primaryArticleSlug: 'bao-hiem-y-te-quoc-dan-giam-phi',
    primaryProblemId: 'prob-job-change',
    primaryToolId: 'leaving-job-wizard-jp',
  },
  {
    id: 'visa-renewal',
    name: 'Gia hạn & Đổi visa (ビザ更新)',
    category: 'doc',
    japanese: ['在留期間更新', 'ビザ更新', '在職証明書', '入国管理局'],
    romaji: ['koushin', 'visa koushin', 'zaishoku shomeisho', 'nyukan'],
    vietnamese: [
      'gia hạn visa',
      'gia han visa',
      'visa kỹ sư',
      'đổi visa',
      'hết hạn visa',
      'nộp hồ sơ nyukan',
      'xin giấy công ty',
      'chứng nhận làm việc',
      'trước 3 tháng',
    ],
    typos: ['gia han visa', 'visa ky su', 'nyukan visa', 'thoi han visa'],
    primaryArticleSlug: 'gia-han-visa-ky-su-truoc-3-thang',
    primaryProblemId: 'prob-renew-visa',
    primaryToolId: 'residence-renewal-guide-jp',
  },
  {
    id: 'tax-adjustment',
    name: 'Khai thuế cuối năm (年末調整)',
    category: 'work',
    japanese: ['年末調整', '確定申告', '扶養控除', '送金証明書'],
    romaji: ['nenmatsu chosei', 'kakutei shinkoku', 'fuyou koujo', 'soukin'],
    vietnamese: [
      'khai thuế cuối năm',
      'nenmatsu chosei',
      'gửi tiền về nhà',
      'gui tien ve nha',
      'người phụ thuộc',
      'fuyo',
      'hoàn thuế',
      'chứng từ chuyển tiền',
      'giảm trừ gia cảnh',
    ],
    typos: ['khai thue', 'nenmatsu', 'fuyo nhat', 'hoan thue cuoi nam'],
    primaryArticleSlug: 'khai-thue-cuoi-nam-gui-tien-ve-nha',
    primaryProblemId: 'prob-tax',
    primaryToolId: 'japan-tax-simulator',
  },
  {
    id: 'child-birth',
    name: 'Sinh con & Trẻ em (出産・育児)',
    category: 'health',
    japanese: ['出産育児一時金', '妊婦健診', '出産', '育児休業'],
    romaji: ['shussan', 'ikuji', 'shussan ikuji ichijikin'],
    vietnamese: [
      'sinh con',
      'sinh em bé',
      'mang thai',
      'chi phí sinh con',
      'trợ cấp sinh con',
      'nghỉ thai sản',
      'sinh con ở nhật',
      'con sắp vào tiểu học',
    ],
    typos: ['sinh con o nhat', 'tro cap de', 'mang bau o nhat'],
    primaryToolId: 'maternity-allowance-jp',
    primaryProblemId: 'prob-newcomer',
  },
  {
    id: 'medical-visit',
    name: 'Đi khám bệnh & Triệu chứng (病院・診察)',
    category: 'health',
    japanese: ['病院', '問診票', '症状', '発熱', '救急車'],
    romaji: ['byouin', 'monshinhyou', 'shoujou', 'kyuukyuusha'],
    vietnamese: [
      'đi khám bệnh',
      'kham benh',
      'triệu chứng',
      'đau bụng',
      'đau đầu',
      'sốt cao',
      'phiếu khám monshinhyo',
      'bệnh viện nhật',
      'gặp bác sĩ',
    ],
    typos: ['di kham benh', 'trieu chung benh', 'tieng nhat kham benh'],
    primaryArticleSlug: 'di-kham-benh-tu-vung-trieu-chung',
    primaryToolId: 'social-insurance-jp',
  },
];
