/**
 * TOOLIO COMPATIBILITY SNAPSHOT
 *
 * Toolio is the authoritative source of truth.
 *
 * This file exists only because Toolio is LOCKED and
 * currently does not expose a public registry contract
 * for ChottoDay.
 *
 * Do NOT invent, rename, or manually extend Toolio tools.
 *
 * Any change to this snapshot must first be validated
 * against the current Toolio registry.
 *
 * This adapter is intentionally replaceable by a future
 * PublicToolRegistryAdapter without changing Chotto UI.
 */

export const TOOLIO_SNAPSHOT_METADATA = {
  version: '2026.09-phase3',
  source: 'Toolio toolsRegistry',
  totalTools: 56,
  activeTools: 56,
  extractedAt: '2026-09-17T11:53:13.704Z'
};

export const TOOLIO_SNAPSHOT = [
  {
    "id": "business-card-studio",
    "name": "Tạo Danh Thiếp",
    "description": "Thiết kế danh thiếp chuẩn in 300 DPI kèm bù xén 3mm & dấu Tonbo. Quét AI OCR từ ảnh danh thiếp cũ, 28 phong cách và in hàng loạt nhân viên.",
    "domain": "common",
    "subdomain": null,
    "category": "image",
    "route": "#/tools/business-card-studio",
    "status": "active",
    "processing": "browser",
    "tags": [
      "business card",
      "namecard",
      "danh thiếp",
      "meishi",
      "名刺",
      "in ấn",
      "tonbo",
      "トンボ",
      "ocr",
      "vcard",
      "qr",
      "print"
    ]
  },
  {
    "id": "id-photo-studio",
    "name": "Tạo Ảnh Thẻ & Hộ Chiếu",
    "description": "Tách nền AI Studio HD, căn chuẩn khuôn mặt theo lưới ICAO/Combini, xuất file đơn Ultra HD và sheet in 300/600 DPI.",
    "domain": "common",
    "subdomain": null,
    "category": "image",
    "route": "#/tools/id-photo-studio",
    "status": "active",
    "processing": "browser",
    "tags": [
      "id photo",
      "passport",
      "ảnh thẻ",
      "hộ chiếu",
      "combini",
      "cv",
      "visa",
      "ai matting",
      "履歴書"
    ]
  },
  {
    "id": "image-convert",
    "name": "Nén Ảnh Đa Năng",
    "description": "Chuyển đổi hàng loạt PNG, JPG, GIF và WebP, nén dung lượng và so sánh chất lượng trực quan.",
    "domain": "common",
    "subdomain": null,
    "category": "image",
    "route": "#/tools/image-convert",
    "status": "active",
    "processing": "browser",
    "tags": [
      "image",
      "webp",
      "convert",
      "png",
      "jpg",
      "gif",
      "compress",
      "ảnh"
    ]
  },
  {
    "id": "screen-capture",
    "name": "Chụp Màn Hình",
    "description": "Chụp nhanh màn hình, kéo chọn vùng tự động copy Clipboard 1-chạm và biên tập vẽ mũi tên, ghi chú, làm mờ.",
    "domain": "common",
    "subdomain": null,
    "category": "image",
    "route": "#/tools/screen-capture",
    "status": "active",
    "processing": "browser",
    "tags": [
      "screenshot",
      "capture",
      "chụp màn hình",
      "clipboard",
      "snip",
      "annotate",
      "mũi tên",
      "arrow",
      "blur"
    ]
  },
  {
    "id": "screen-recorder",
    "name": "Quay Màn Hình",
    "description": "Ghi video màn hình, cửa sổ hoặc thẻ trình duyệt kèm âm thanh. Hoạt động 100% trên trình duyệt, không tốn RAM, tối ưu cho máy cấu hình thấp.",
    "domain": "common",
    "subdomain": null,
    "category": "utils",
    "route": "#/tools/screen-recorder",
    "status": "active",
    "processing": "browser",
    "tags": [
      "screen-recorder",
      "record",
      "video",
      "quay màn hình",
      "recording",
      "low-spec",
      "screen",
      "audio"
    ]
  },
  {
    "id": "barcode-qr",
    "name": "Tạo Mã QR & Barcode",
    "description": "Tạo mã QR nghệ thuật nhúng logo, gradient màu và mã vạch 1D chuẩn GS1 (Code128, EAN-13, UPC, ITF-14) 100% offline.",
    "domain": "common",
    "subdomain": null,
    "category": "utils",
    "route": "#/tools/barcode-qr",
    "status": "active",
    "processing": "browser",
    "tags": [
      "qr",
      "barcode",
      "mã vạch",
      "mã qr",
      "ean",
      "code128",
      "upc",
      "itf-14",
      "logo",
      "batch",
      "generator"
    ]
  },
  {
    "id": "pdf-toolkit",
    "name": "Công Cụ PDF Đa Năng",
    "description": "Tách, gộp và sắp xếp trang PDF 100% trên trình duyệt.",
    "domain": "common",
    "subdomain": null,
    "category": "pdf",
    "route": "#/tools/pdf-toolkit",
    "status": "active",
    "processing": "browser",
    "tags": [
      "pdf",
      "split",
      "tách",
      "trích xuất",
      "extract",
      "merge",
      "gộp",
      "ghép",
      "combine",
      "organize",
      "sắp xếp"
    ]
  },
  {
    "id": "omniconvert",
    "name": "Chuyển Đổi Đa Năng",
    "description": "Chuyển đổi linh hoạt giữa DOCX, PPTX, XLSX, PDF, Markdown (.md), ảnh và TXT 100% bảo mật trên trình duyệt.",
    "domain": "common",
    "subdomain": null,
    "category": "pdf",
    "route": "#/tools/omniconvert",
    "status": "active",
    "processing": "browser",
    "tags": [
      "convert",
      "pdf",
      "docx",
      "pptx",
      "xlsx",
      "markdown",
      "md",
      "chuyển đổi"
    ]
  },
  {
    "id": "excel-mapping",
    "name": "Tự Động Hóa & Mapping Excel",
    "description": "Tự động ánh xạ các cột dữ liệu Excel của khách hàng vào biểu mẫu nhà cung cấp.",
    "domain": "common",
    "subdomain": null,
    "category": "utils",
    "route": "#/tools/excel-mapping",
    "status": "active",
    "processing": "hybrid",
    "tags": [
      "excel",
      "mapping",
      "xlsx",
      "data",
      "tự động hóa"
    ]
  },
  {
    "id": "editor-studio",
    "name": "Bộ Soạn Thảo Template Nâng Cao",
    "description": "Trình tạo biểu mẫu tương tác, thiết kế dàn trang A4 và xuất file DOCX/PDF.",
    "domain": "common",
    "subdomain": null,
    "category": "pdf",
    "route": "#/tools/editor-studio",
    "status": "active",
    "processing": "browser",
    "tags": [
      "editor",
      "template",
      "docx",
      "form",
      "soạn thảo"
    ]
  },
  {
    "id": "invoice-studio",
    "name": "Tạo Đề Nghị Thanh Toán",
    "description": "Trích xuất dữ liệu hóa đơn điện tử XML/PDF và tự động xuất bảng Excel Đề nghị thanh toán.",
    "domain": "common",
    "subdomain": null,
    "category": "office",
    "route": "#/tools/invoice-studio",
    "status": "active",
    "processing": "browser",
    "tags": [
      "invoice",
      "hóa đơn",
      "thanh toán",
      "xml",
      "pdf",
      "excel"
    ]
  },
  {
    "id": "invoice-xml-fetcher",
    "name": "Lấy Hóa Đơn XML",
    "description": "Đọc mã tra cứu và link từ PDF hóa đơn, tải XML trực tiếp hoặc hỗ trợ 1 chạm mở cổng tra cứu.",
    "domain": "common",
    "subdomain": null,
    "category": "office",
    "route": "#/tools/invoice-xml-fetcher",
    "status": "active",
    "processing": "browser",
    "tags": [
      "invoice",
      "hóa đơn",
      "xml",
      "tra cứu",
      "pdf",
      "minvoice",
      "hilo",
      "vnpt",
      "viettel",
      "misa"
    ]
  },
  {
    "id": "accounting-reconcile",
    "name": "Đối Chiếu Kế Toán",
    "description": "Tự động đối chiếu chênh lệch doanh thu và thuế GTGT giữa sổ kế toán nội bộ (511, 33311) và bảng kê thuế (BR).",
    "domain": "common",
    "subdomain": null,
    "category": "office",
    "route": "#/tools/accounting-reconcile",
    "status": "active",
    "processing": "browser",
    "tags": [
      "accounting",
      "reconcile",
      "đối chiếu",
      "kế toán",
      "thuế",
      "doanh thu",
      "511",
      "33311",
      "br",
      "excel"
    ]
  },
  {
    "id": "tax-calculator",
    "name": "Tính Thuế TNCN",
    "description": "Tính thuế TNCN lũy tiến 5 bậc 2026, chuyển đổi Gross ↔ Net, mức giảm trừ mới, bảo hiểm 4 vùng, tính thuế Freelancer, BĐS và BHXH rút 1 lần.",
    "domain": "common",
    "subdomain": null,
    "category": "office",
    "route": "#/tools/tax-calculator",
    "status": "active",
    "processing": "browser",
    "tags": [
      "thuế tncn",
      "tax",
      "pit",
      "gross net",
      "lương",
      "salary",
      "bhxh",
      "bhtn",
      "quuyết toán",
      "freelancer",
      "bất động sản",
      "office"
    ]
  },
  {
    "id": "japan-tax-simulator",
    "name": "Mô Phỏng Thuế Nhật Bản",
    "description": "Mô phỏng toàn diện các loại thuế & bảo hiểm xã hội Nhật Bản (Thuế TNCN, Thuế cư trú, Kinh doanh, Tiêu thụ, Pháp nhân). Chẩn đoán tự động điều kiện kê khai 確定申告 & mô phỏng What-If. 100% xử lý nội bộ trình duyệt.",
    "domain": "japan-life",
    "subdomain": "tax",
    "category": "office",
    "route": "#/tools/japan-tax-simulator",
    "status": "active",
    "processing": "browser",
    "tags": [
      "japan tax",
      "thuế nhật",
      "日本の税金",
      "確定申告",
      "所得税",
      "住民税",
      "個人事業税",
      "消費税",
      "法人税",
      "社会保険",
      "gensen",
      "nenkin",
      "hoken",
      "shinkoku",
      "office"
    ]
  },
  {
    "id": "social-insurance-jp",
    "name": "Mô Phỏng BHXH Nhật Bản",
    "description": "Mô phỏng chính xác BHYT Kyokai Kenpo (47 tỉnh thành), Quỹ hỗ trợ nuôi con 2026, Chăm sóc người già, Hưu trí Kosei Nenkin & Thất nghiệp theo bảng chuẩn thù lao tháng. 100% xử lý nội bộ trình duyệt.",
    "domain": "japan-life",
    "subdomain": "insurance",
    "category": "office",
    "route": "#/tools/social-insurance-jp",
    "status": "active",
    "processing": "browser",
    "tags": [
      "社会保険",
      "健康保険",
      "厚生年金",
      "雇用保険",
      "介護保険",
      "子ども子育て支援金",
      "標準報酬月額",
      "insurance",
      "pension",
      "bảo hiểm",
      "lương hưu",
      "kenpo",
      "shakai hoken",
      "japan life",
      "office"
    ]
  },
  {
    "id": "social-insurance-eligibility-jp",
    "name": "Kiểm Tra Điều Kiện Tham Gia BHXH",
    "description": "Chẩn đoán điều kiện bắt buộc tham gia BHXH (BHYT & Hưu trí Kosei Nenkin) cho lao động Part-time, Baito theo quy chuẩn mở rộng 2026 (20h/tuần, 8.8 vạn, DN 51 người). 100% xử lý nội bộ trình duyệt.",
    "domain": "japan-life",
    "subdomain": "insurance",
    "category": "office",
    "route": "#/tools/social-insurance-eligibility-jp",
    "status": "active",
    "processing": "browser",
    "tags": [
      "社会保険加入判定",
      "社会保険",
      "106万円の壁",
      "短時間労働者",
      "パート",
      "アルバイト",
      "厚生年金",
      "健康保険",
      "eligibility",
      "insurance",
      "bảo hiểm",
      "lương hưu",
      "shakai hoken",
      "japan life",
      "office"
    ]
  },
  {
    "id": "national-pension-jp",
    "name": "Tra Cứu & Tính Phí Hưu Trí Quốc Dân",
    "description": "Tra cứu biểu phí Hưu trí Quốc dân FY2026 (17,920円/tháng), mức chiết khấu nộp trước (前納), tỷ lệ hưởng lương hưu theo các mức miễn giảm (免除・猶予) và quy tắc truy đóng (追納). 100% xử lý nội bộ trình duyệt.",
    "domain": "japan-life",
    "subdomain": "insurance",
    "category": "office",
    "route": "#/tools/national-pension-jp",
    "status": "active",
    "processing": "browser",
    "tags": [
      "国民年金",
      "年金",
      "保険料",
      "前納",
      "免除",
      "納付猶予",
      "学生納付特例",
      "追納",
      "付加年金",
      "pension",
      "insurance",
      "hưu trí",
      "lương hưu",
      "bảo hiểm",
      "japan life",
      "office"
    ]
  },
  {
    "id": "dependent-insurance-jp",
    "name": "Kiểm Tra Người Phụ Thuộc BHXH",
    "description": "Chẩn đoán điều kiện làm người phụ thuộc BHYT (0円 phí bảo hiểm) theo quan hệ thân nhân 3 đời, sống chung/riêng, trần thu nhập tương lai 130 vạn/180 vạn và tỷ lệ chu cấp. Phân biệt độc lập với thuế. 100% xử lý nội bộ trình duyệt.",
    "domain": "japan-life",
    "subdomain": "insurance",
    "category": "office",
    "route": "#/tools/dependent-insurance-jp",
    "status": "active",
    "processing": "browser",
    "tags": [
      "社会保険の扶養判定",
      "社会保険",
      "被扶養者",
      "130万円の壁",
      "180万円の壁",
      "健康保険",
      "国民年金第3号",
      "扶養",
      "dependent",
      "insurance",
      "pension",
      "bảo hiểm",
      "lương hưu",
      "japan life",
      "office"
    ]
  },
  {
    "id": "overtime-calculator-jp",
    "name": "Tính Tiền Làm Thêm Giờ (残業代)",
    "description": "Mô phỏng chính xác tiền lương phụ trội làm thêm giờ (ngoài giờ 25%, vượt 60h/tháng 50%, làm đêm 25%, ngày nghỉ 35%). Chuẩn Điều 37 Luật Tiêu chuẩn Lao động Nhật Bản. 100% xử lý nội bộ trình duyệt.",
    "domain": "japan-life",
    "subdomain": "employment",
    "category": "office",
    "route": "#/tools/overtime-calculator-jp",
    "status": "active",
    "processing": "browser",
    "tags": [
      "残業代シミュレーター",
      "残業代",
      "割増賃金",
      "時間外労働",
      "休日労働",
      "深夜労働",
      "60時間超",
      "overtime",
      "tăng ca",
      "làm thêm giờ",
      "tiền tăng ca",
      "zangyou",
      "japan life",
      "office"
    ]
  },
  {
    "id": "paid-leave-checker-jp",
    "name": "Kiểm Tra Phép Năm (有給休暇)",
    "description": "Tra cứu ngày nghỉ phép có lương theo thâm niên, lịch cấp phép tỷ lệ cho part-time/baito, điều kiện chuyên cần 80% và nghĩa vụ nghỉ 5 ngày/năm. Chuẩn Điều 39 Luật Tiêu chuẩn Lao động.",
    "domain": "japan-life",
    "subdomain": "employment",
    "category": "office",
    "route": "#/tools/paid-leave-checker-jp",
    "status": "active",
    "processing": "browser",
    "tags": [
      "有給休暇チェッカー",
      "有給休暇",
      "年次有給休暇",
      "有給",
      "年5日取得義務",
      "比例付与",
      "出勤率8割",
      "paid leave",
      "annual leave",
      "phép năm",
      "nghỉ phép",
      "yukyu",
      "japan life",
      "office"
    ]
  },
  {
    "id": "unemployment-eligibility-jp",
    "name": "Điều Kiện Trợ Cấp Thất Nghiệp (失業給付)",
    "description": "Kiểm tra điều kiện hưởng trợ cấp thất nghiệp, phân loại diện thôi việc (công ty sa thải 6 tháng vs tự ý nghỉ 12 tháng), thời gian hạn chế chi trả (0 vs 2 tháng), và thủ tục gia hạn tối đa 4 năm.",
    "domain": "japan-life",
    "subdomain": "employment",
    "category": "office",
    "route": "#/tools/unemployment-eligibility-jp",
    "status": "active",
    "processing": "browser",
    "tags": [
      "失業給付受給資格チェッカー",
      "失業給付",
      "受給資格",
      "基本手当",
      "雇用保険",
      "特定受給資格者",
      "特定理由離職者",
      "給付制限",
      "受給期間延長",
      "離職票",
      "unemployment",
      "thất nghiệp",
      "trợ cấp thất nghiệp",
      "hello work",
      "japan life",
      "office"
    ]
  },
  {
    "id": "unemployment-benefit-jp",
    "name": "Mô Phỏng Trợ Cấp Thất Nghiệp (失業給付)",
    "description": "Tính toán chính xác mức trợ cấp cơ bản hàng ngày (基本手当日額), số ngày hưởng (90〜330 ngày), tổng số tiền nhận và tỷ lệ trượt 50%〜80% theo luật MHLW. 100% xử lý trên trình duyệt.",
    "domain": "japan-life",
    "subdomain": "employment",
    "category": "office",
    "route": "#/tools/unemployment-benefit-jp",
    "status": "active",
    "processing": "browser",
    "tags": [
      "失業給付シミュレーター",
      "失業手当",
      "失業保険",
      "基本手当日額",
      "賃金日額",
      "所定給付日数",
      "受給総額",
      "給付率",
      "unemployment",
      "trợ cấp thất nghiệp",
      "tiền thất nghiệp",
      "thất nghiệp",
      "japan life",
      "office"
    ]
  },
  {
    "id": "leaving-job-wizard-jp",
    "name": "Hướng Dẫn Nghỉ Việc Tại Nhật",
    "description": "Điều phối toàn diện thủ tục khi thôi việc: thời hạn báo trước 14 ngày, 3 lựa chọn BHYT, chuyển đổi lương hưu quốc dân, khấu trừ thuế cư trú và hồ sơ Hello Work.",
    "domain": "japan-life",
    "subdomain": "employment",
    "category": "office",
    "route": "#/tools/leaving-job-wizard-jp",
    "status": "active",
    "processing": "browser",
    "tags": [
      "退職手続き",
      "退職",
      "退職届",
      "離職票",
      "任意継続",
      "国民健康保険",
      "国民年金",
      "住民税",
      "一括徴収",
      "ハローワーク",
      "resignation",
      "leaving job",
      "nghỉ việc",
      "thôi việc",
      "thủ tục thôi việc",
      "japan life",
      "office"
    ]
  },
  {
    "id": "maternity-allowance-jp",
    "name": "Tính Trợ Cấp Thai Sản",
    "description": "Mô phỏng trợ cấp thai sản BHYT Nhật Bản (2/3 lương chuẩn): tính chính xác số ngày được hưởng, mức trợ cấp ngày và tổng số tiền.",
    "domain": "japan-life",
    "subdomain": "family",
    "category": "office",
    "route": "#/tools/maternity-allowance-jp",
    "status": "active",
    "processing": "browser",
    "tags": [
      "出産手当金",
      "産前産後休業",
      "健康保険",
      "協会けんぽ",
      "thai sản",
      "maternity allowance",
      "nghỉ sinh",
      "trợ cấp thai sản",
      "lương nghỉ thai sản",
      "bảo hiểm thai sản",
      "japan life",
      "family"
    ]
  },
  {
    "id": "childcare-leave-eligibility-jp",
    "name": "Kiểm Tra Nghỉ Chăm Con & Trợ Cấp",
    "description": "Chẩn đoán quyền nghỉ chăm con theo luật lao động & điều kiện nhận 4 chế độ trợ cấp BHTN (tiêu chuẩn, sau sinh cho bố, thưởng 13%, rút ngắn giờ).",
    "domain": "japan-life",
    "subdomain": "family",
    "category": "office",
    "route": "#/tools/childcare-leave-eligibility-jp",
    "status": "active",
    "processing": "browser",
    "tags": [
      "育児休業",
      "育児休業給付金",
      "産後パパ育休",
      "出生後休業支援給付金",
      "育児時短就業給付金",
      "雇用保険",
      "育休",
      "childcare leave",
      "nghỉ chăm con",
      "trợ cấp chăm con",
      "japan life",
      "family"
    ]
  },
  {
    "id": "childcare-benefit-jp",
    "name": "Tính Trợ Cấp Nghỉ Chăm Con",
    "description": "Mô phỏng tiền trợ cấp nghỉ chăm con (giai đoạn 67% và 50%), tiền hỗ trợ sau sinh 13%, trợ cấp rút ngắn giờ làm 10% và miễn giảm bảo hiểm xã hội.",
    "domain": "japan-life",
    "subdomain": "family",
    "category": "office",
    "route": "#/tools/childcare-benefit-jp",
    "status": "active",
    "processing": "browser",
    "tags": [
      "育児休業給付金",
      "育児休業",
      "育休手当",
      "出生後休業支援給付金",
      "育児時短就業給付金",
      "社会保険料免除",
      "非課税",
      "雇用保険",
      "childcare benefit",
      "trợ cấp nghỉ chăm con",
      "bảo hiểm thất nghiệp",
      "japan life",
      "family"
    ]
  },
  {
    "id": "child-allowance-jp",
    "name": "Kiểm Tra Trợ Cấp Trẻ Em",
    "description": "Chẩn đoán số tiền trợ cấp trẻ em theo cải cách 10/2024: Bỏ trần thu nhập, mở rộng đến 18 tuổi (hết cấp 3), con thứ 3 nhận 30.000円/tháng, đếm thứ tự con đến 22 tuổi.",
    "domain": "japan-life",
    "subdomain": "family",
    "category": "office",
    "route": "#/tools/child-allowance-jp",
    "status": "active",
    "processing": "browser",
    "tags": [
      "児童手当",
      "こども家庭庁",
      "所得制限撤廃",
      "多子加算",
      "第3子",
      "高校生年代",
      "child allowance",
      "trợ cấp trẻ em",
      "trợ cấp nuôi con",
      "japan life",
      "family"
    ]
  },
  {
    "id": "birth-wizard-jp",
    "name": "Cẩm Nang Mang Thai & Nuôi Con",
    "description": "Bản đồ lộ trình 6 giai đoạn từ lúc mang thai đến con 2 tuổi: Tính khoản hỗ trợ sinh con 500.000円, hạn nộp hồ sơ, cơ quan phụ trách và chính sách riêng theo địa phương.",
    "domain": "japan-life",
    "subdomain": "family",
    "category": "office",
    "route": "#/tools/birth-wizard-jp",
    "status": "active",
    "processing": "browser",
    "tags": [
      "妊娠",
      "出産",
      "育児",
      "出産育児一時金",
      "母子手帳",
      "保活",
      "出生届",
      "birth wizard",
      "mang thai",
      "sinh con",
      "nuôi con",
      "japan life",
      "family"
    ]
  },
  {
    "id": "moving-cost-jp",
    "name": "Mô Phỏng Chi Phí Chuyển Nhà",
    "description": "Ước tính cước phí chuyển nhà theo quy mô hộ gia đình, cự ly và mùa cao điểm. Tra cứu biểu phí phạt hủy hợp đồng theo quy ước chuẩn của Bộ Giao thông MLIT.",
    "domain": "japan-life",
    "subdomain": "housing",
    "category": "office",
    "route": "#/tools/moving-cost-jp",
    "status": "active",
    "processing": "browser",
    "tags": [
      "引越し",
      "引越し費用",
      "相場",
      "トラック",
      "標準引越運送約款",
      "moving cost",
      "chuyển nhà",
      "cước phí",
      "japan life",
      "housing"
    ]
  },
  {
    "id": "moving-admin-checker-jp",
    "name": "Thủ Tục Hành Chính Chuyển Nhà",
    "description": "Kiểm tra hạn chót luật định 14 ngày cho 転出届 (chuyển đi), 転入届 (chuyển đến), 転居届 (đổi địa chỉ). Hướng dẫn dịch vụ Một Cửa chuyển nhà online trên MyNaPortal.",
    "domain": "japan-life",
    "subdomain": "housing",
    "category": "office",
    "route": "#/tools/moving-admin-checker-jp",
    "status": "active",
    "processing": "browser",
    "tags": [
      "引越し",
      "転出届",
      "転入届",
      "転居届",
      "マイナポータル",
      "ワンストップ",
      "住民基本台帳法",
      "moving procedure",
      "thủ tục chuyển nhà",
      "chuyển khẩu",
      "japan life",
      "housing"
    ]
  },
  {
    "id": "address-change-checklist-jp",
    "name": "Checklist Đổi Địa Chỉ Đa Kênh",
    "description": "Quản lý đổi địa chỉ chuyển tiếp Bưu điện (e-Tenkyo 1 năm), Điện, Ga (đặt hẹn mở van an toàn), Nước, Internet cáp quang, Bằng lái, Ngân hàng và Thẻ.",
    "domain": "japan-life",
    "subdomain": "housing",
    "category": "office",
    "route": "#/tools/address-change-checklist-jp",
    "status": "active",
    "processing": "browser",
    "tags": [
      "引越し",
      "住所変更",
      "e転居",
      "郵便局",
      "ライフライン",
      "電気",
      "ガス",
      "水道",
      "address change",
      "đổi địa chỉ",
      "chuyển nhà",
      "japan life",
      "housing"
    ]
  },
  {
    "id": "moving-wizard-jp",
    "name": "Lộ Trình Thủ Tục Chuyển Nhà",
    "description": "Điều phối toàn diện thủ tục chuyển nhà: Lập tiến trình trước & sau chuyển, cảnh báo hạn 14 ngày & phạt 50.000 yên, đặc lệ 15 ngày trợ cấp trẻ em, e-Tenkyo và điện nước gas.",
    "domain": "japan-life",
    "subdomain": "housing",
    "category": "office",
    "route": "#/tools/moving-wizard-jp",
    "status": "active",
    "processing": "browser",
    "tags": [
      "引越し",
      "手続き",
      "ガイド",
      "転入届",
      "転出届",
      "過料",
      "児童手当",
      "ライフライン",
      "e転居",
      "moving guide",
      "chuyển nhà",
      "japan life",
      "housing"
    ]
  },
  {
    "id": "work-scope-checker-jp",
    "name": "Kiểm Tra Phạm Vi Làm Việc Visa",
    "description": "Đối chiếu tư cách lưu trú (kỹ sư, du học, gia đình, vĩnh trú...) với công việc dự kiến theo chuẩn ISA. Xác định điều kiện Giấy phép làm thêm (資格外活動許可) và trần 28h/tuần.",
    "domain": "japan-life",
    "subdomain": "immigration",
    "category": "office",
    "route": "#/tools/work-scope-checker-jp",
    "status": "active",
    "processing": "browser",
    "tags": [
      "在留資格",
      "就労範囲",
      "ビザ",
      "資格外活動許可",
      "週28時間",
      "技人国",
      "留学",
      "家族滞在",
      "永住者",
      "入管",
      "work scope",
      "residence status",
      "visa nhật",
      "phạm vi làm việc",
      "japan life",
      "immigration"
    ]
  },
  {
    "id": "residence-renewal-guide-jp",
    "name": "Hướng Dẫn Gia Hạn Lưu Trú",
    "description": "Tính toán cửa sổ nộp hồ sơ gia hạn (3 tháng trước), thời kỳ đặc lệ (Tokurei Kikan), lệ phí và danh mục hồ sơ giấy tờ.",
    "domain": "japan-life",
    "subdomain": "immigration",
    "category": "office",
    "route": "#/tools/residence-renewal-guide-jp",
    "status": "active",
    "processing": "browser",
    "tags": [
      "visa",
      "immigration",
      "renewal",
      "tokurei",
      "gia hạn",
      "thẻ cư trú",
      "isa",
      "在留期間更新",
      "入管",
      "japan life"
    ]
  },
  {
    "id": "affiliation-change-checker-jp",
    "name": "Kiểm Tra Thay Đổi Đơn Vị Công Tác",
    "description": "Tính toán hạn thông báo 14 ngày (Điều 19-16), đánh giá nguy cơ thu hồi tư cách sau 3 tháng không hoạt động, và hướng dẫn xin Giấy chứng nhận tư cách làm việc.",
    "domain": "japan-life",
    "subdomain": "immigration",
    "category": "office",
    "route": "#/tools/affiliation-change-checker-jp",
    "status": "active",
    "processing": "browser",
    "tags": [
      "chuyển việc",
      "thay đổi công ty",
      "thông báo 14 ngày",
      "thu hồi visa",
      "hello work",
      "転職",
      "所属機関変更",
      "入管",
      "就労資格証明書",
      "japan life"
    ]
  },
  {
    "id": "status-change-guide-jp",
    "name": "Hướng Dẫn Đổi Tư Cách Lưu Trú",
    "description": "Hướng dẫn điều kiện pháp định, thẩm định hồ sơ và tính toán thời hạn đặc lệ khi đổi visa (Điều 20 Luật Nhập quản).",
    "domain": "japan-life",
    "subdomain": "immigration",
    "category": "office",
    "route": "#/tools/status-change-guide-jp",
    "status": "active",
    "processing": "browser",
    "tags": [
      "visa",
      "immigration",
      "status change",
      "henkou",
      "đổi visa",
      "gijinkoku",
      "chuyển visa",
      "tokurei",
      "在留資格変更",
      "入管",
      "japan life"
    ]
  },
  {
    "id": "family-immigration-guide-jp",
    "name": "Hướng Dẫn Bảo Lãnh Gia Đình",
    "description": "Hướng dẫn bảo lãnh vợ/chồng, con cái sang Nhật (COE), thủ tục cho trẻ mới sinh tại Nhật (Điều 22-2) và quy định làm thêm 28h.",
    "domain": "japan-life",
    "subdomain": "immigration",
    "category": "office",
    "route": "#/tools/family-immigration-guide-jp",
    "status": "active",
    "processing": "browser",
    "tags": [
      "visa",
      "immigration",
      "family",
      "kazoku taizai",
      "dependent",
      "bảo lãnh",
      "gia đình",
      "coe",
      "28h",
      "家族滞在",
      "入管",
      "japan life"
    ]
  },
  {
    "id": "pr-readiness-checker-jp",
    "name": "Đánh Giá Điều Kiện Vĩnh Trú",
    "description": "Tự đánh giá 6 điều kiện xin Vĩnh trú Nhật Bản: thời gian cư trú, thời hạn visa 3-5 năm, lịch sử đóng thuế, Nenkin & BHYT 2-5 năm không trễ hạn.",
    "domain": "japan-life",
    "subdomain": "immigration",
    "category": "office",
    "route": "#/tools/pr-readiness-checker-jp",
    "status": "active",
    "processing": "browser",
    "tags": [
      "visa",
      "immigration",
      "permanent residence",
      "eijuu",
      "vĩnh trú",
      "nenkin",
      "tax",
      "hsp",
      "tokurei",
      "永住許可",
      "入管",
      "japan life"
    ]
  },
  {
    "id": "arriving-in-japan-wizard-jp",
    "name": "Hướng Dẫn Cho Người Mới Sang Nhật",
    "description": "Lộ trình hướng dẫn các thủ tục pháp định tại sân bay, tòa thị chính trong 14 ngày (đăng ký địa chỉ, My Number, Nenkin/BHYT), mở ngân hàng, SIM và thủ tục công ty.",
    "domain": "japan-life",
    "subdomain": "immigration",
    "category": "office",
    "route": "#/tools/arriving-in-japan-wizard-jp",
    "status": "active",
    "processing": "browser",
    "tags": [
      "visa",
      "immigration",
      "arrival",
      "newcomer",
      "mới sang nhật",
      "14 ngày",
      "tòa thị chính",
      "yucho",
      "sim",
      "來日",
      "住民登録",
      "入管",
      "japan life"
    ]
  },
  {
    "id": "leaving-japan-wizard-jp",
    "name": "Thủ Tục Khi Rời Khỏi Nhật Bản",
    "description": "Lộ trình hướng dẫn thủ tục xuất cảnh tạm thời (Minashi Re-entry) hoặc rời Nhật hẳn (chuyển đi, My Number, người đại diện thuế, rút Nenkin 1 lần & hoàn 20.42% thuế).",
    "domain": "japan-life",
    "subdomain": "immigration",
    "category": "office",
    "route": "#/tools/leaving-japan-wizard-jp",
    "status": "active",
    "processing": "browser",
    "tags": [
      "visa",
      "immigration",
      "leaving japan",
      "re-entry",
      "minashi",
      "rời nhật",
      "về nước",
      "nenkin",
      "hoàn thuế",
      "20.42%",
      "脱退一時金",
      "再入国",
      "japan life"
    ]
  },
  {
    "id": "watermark-studio",
    "name": "Đóng Dấu Tài Liệu",
    "description": "Đóng dấu watermark văn bản hoặc logo lên PDF, DOCX, XLSX, PPTX và ảnh. Tùy chỉnh màu sắc, độ đậm nhạt, bố cục lưới/đơn. 100% xử lý trên trình duyệt.",
    "domain": "common",
    "subdomain": null,
    "category": "utils",
    "route": "#/tools/watermark-studio",
    "status": "active",
    "processing": "browser",
    "tags": [
      "watermark",
      "stamp",
      "đóng dấu",
      "bản quyền",
      "confidential",
      "draft",
      "logo",
      "pdf",
      "docx",
      "xlsx",
      "pptx",
      "ảnh"
    ]
  },
  {
    "id": "flappy-bird",
    "name": "Flappy Bird",
    "description": "Minigame giải trí thư giãn, điều khiển chú chim bay qua các đường ống.",
    "domain": "common",
    "subdomain": null,
    "category": "utils",
    "route": "#/tools/flappy-bird",
    "status": "active",
    "processing": "browser",
    "tags": [
      "flappy bird",
      "game",
      "minigame",
      "chim bay",
      "arcade",
      "giải trí",
      "relax",
      "utils"
    ]
  },
  {
    "id": "toolio-ninja",
    "name": "Toolio Ninja Run",
    "description": "Endless runner vui nhộn: cùng Ninja vượt dặm trường Nhật - Việt, né tránh và chém tan các vấn đề văn phòng!",
    "domain": "common",
    "subdomain": null,
    "category": "utils",
    "route": "#/tools/toolio-ninja",
    "status": "active",
    "processing": "browser",
    "tags": [
      "game",
      "minigame",
      "ninja",
      "runner",
      "endless runner",
      "arcade",
      "giải trí",
      "relax",
      "chém",
      "jump",
      "slash",
      "pdf",
      "toolio"
    ]
  },
  {
    "id": "document-finder-jp",
    "name": "Tra Cứu Hồ Sơ Giấy Tờ",
    "description": "Tra cứu danh mục giấy tờ bắt buộc, có điều kiện theo thủ tục hành chính (visa, trợ cấp, chuyển nhà, thất nghiệp).",
    "domain": "japan-life",
    "subdomain": "procedures-documents",
    "category": "office",
    "route": "#/tools/document-finder-jp",
    "status": "active",
    "processing": "browser",
    "tags": [
      "giấy tờ",
      "hồ sơ",
      "document",
      "certificate",
      "住民票",
      "課税証明",
      "thủ tục",
      "visa",
      "hành chính",
      "pháp lý",
      "nhật bản"
    ]
  },
  {
    "id": "certificate-acquisition-guide-jp",
    "name": "Hướng Dẫn Lấy Giấy Tờ",
    "description": "Hướng dẫn lấy 住民票, 課税証明, 納税証明, 戸籍, 印鑑, 源泉徴収 qua quầy Tòa thị chính, combini hoặc bưu điện.",
    "domain": "japan-life",
    "subdomain": "procedures-documents",
    "category": "office",
    "route": "#/tools/certificate-acquisition-guide-jp",
    "status": "active",
    "processing": "browser",
    "tags": [
      "lấy giấy tờ",
      "combini",
      "tòa thị chính",
      "shiyakusho",
      "住民票",
      "コンビニ交付",
      "戸籍謄本",
      "hộ tịch",
      "giấy thuế",
      "in ấn"
    ]
  },
  {
    "id": "mynumber-procedure-guide-jp",
    "name": "Thủ Tục Thẻ My Number",
    "description": "Hướng dẫn gia hạn thẻ My Number khi đổi visa, mở khóa mã PIN, cập nhật địa chỉ và hotline 24/7 khi mất thẻ.",
    "domain": "japan-life",
    "subdomain": "procedures-documents",
    "category": "office",
    "route": "#/tools/mynumber-procedure-guide-jp",
    "status": "active",
    "processing": "browser",
    "tags": [
      "my number",
      "mã số cá nhân",
      "thẻ",
      "chứng thư số",
      "mã pin",
      "khóa mã pin",
      "mất thẻ",
      "マイナンバー",
      "電子証明書"
    ]
  },
  {
    "id": "official-form-helper-jp",
    "name": "Trợ Lý Điền Mẫu Đơn Công Quyền",
    "description": "Giải thích chi tiết từng ô của đơn xin gia hạn visa, chuyển nhà, trợ cấp trẻ em và chuẩn bị bản nháp an toàn.",
    "domain": "japan-life",
    "subdomain": "procedures-documents",
    "category": "pdf",
    "route": "#/tools/official-form-helper-jp",
    "status": "active",
    "processing": "browser",
    "tags": [
      "mẫu đơn",
      "điền đơn",
      "form helper",
      "application form",
      "pdf",
      "申請書",
      "giải thích ô",
      "nháp đơn"
    ]
  },
  {
    "id": "procedure-requirement-checker-jp",
    "name": "Kiểm Tra Hồ Sơ Thủ Tục",
    "description": "Tự đánh giá 3 chiều: Thời hạn nộp, độ tươi giấy tờ (trong 3 tháng) và chuẩn bị lệ phí trước khi đi nộp hồ sơ.",
    "domain": "japan-life",
    "subdomain": "procedures-documents",
    "category": "office",
    "route": "#/tools/procedure-requirement-checker-jp",
    "status": "active",
    "processing": "browser",
    "tags": [
      "checker",
      "kiểm tra hồ sơ",
      "đủ giấy tờ",
      "độ tươi",
      "hết hạn",
      "readiness",
      "要件チェック",
      "thủ tục"
    ]
  },
  {
    "id": "administrative-navigator-jp",
    "name": "Điều Hướng Thủ Tục & Giấy Tờ",
    "description": "Cổng tra cứu thông minh về giấy tờ công quyền Nhật Bản, phân biệt các loại giấy thuế, hộ tịch và điều hướng.",
    "domain": "japan-life",
    "subdomain": "procedures-documents",
    "category": "office",
    "route": "#/tools/administrative-navigator-jp",
    "status": "active",
    "processing": "browser",
    "tags": [
      "navigator",
      "điều hướng",
      "tìm kiếm",
      "hành chính",
      "search",
      "thuế",
      "hộ tịch",
      "giấy tờ",
      "ナビ"
    ]
  },
  {
    "id": "japan-life-navigator",
    "name": "Japan Life Navigator",
    "description": "Điều hướng thông minh các sự kiện đời sống tại Nhật Bản (Chuyển việc, Đến Nhật, Sinh con, Đổi nhà, Bảo lãnh gia đình).",
    "domain": "japan-life",
    "subdomain": "navigator",
    "category": "office",
    "route": "#/tools/japan-life-navigator",
    "status": "active",
    "processing": "browser",
    "tags": [
      "navigator",
      "điều hướng",
      "chuyển việc",
      "đến nhật",
      "sinh con",
      "chuyển nhà",
      "bảo lãnh",
      "life events",
      "ナビ"
    ]
  },
  {
    "id": "vietnam-consular-jp",
    "name": "Thủ tục Lãnh sự Việt Nam tại Nhật",
    "description": "Tra cứu thẩm quyền 47 tỉnh thành (Tokyo/Osaka/Fukuoka), hướng dẫn 20 thủ tục lãnh sự thiết yếu (hộ chiếu, khai sinh, kết hôn, hợp pháp hóa), điền và in biểu mẫu chuẩn hóa A4.",
    "domain": "japan-life",
    "subdomain": "consular-vn",
    "category": "office",
    "route": "#/tools/vietnam-consular-jp",
    "status": "active",
    "processing": "browser",
    "tags": [
      "lãnh sự",
      "hộ chiếu",
      "khai sinh",
      "kết hôn",
      "ủy quyền",
      "hợp pháp hóa",
      "đại sứ quán",
      "tổng lãnh sự",
      "consular",
      "passport",
      "visa"
    ]
  },
  {
    "id": "salary-calculator-vn",
    "name": "Tính Lương Gross ↔ Net",
    "description": "Chuyển đổi hai chiều Gross ↔ Net theo luật mới 2026. Tính chi tiết BHXH/BHYT/BHTN, thuế TNCN theo biểu 5 bậc mới (NQ 110/2025) và chi phí thực tế của doanh nghiệp.",
    "domain": "vietnam-life",
    "subdomain": "tax",
    "category": "office",
    "route": "#/tools/salary-calculator-vn",
    "status": "active",
    "processing": "browser",
    "tags": [
      "lương",
      "salary",
      "gross net",
      "gross",
      "net",
      "tính lương",
      "bhxh",
      "thuế tncn",
      "vietnam life",
      "việt nam"
    ]
  },
  {
    "id": "loan-apr-calculator-vn",
    "name": "Tính Lãi Suất Thực Khoản Vay (APR & EAR)",
    "description": "Tính lãi suất thực tế khoản vay (APR/EAR) từ dòng tiền trả góp thực tế (IRR). Bóc tách phí bảo hiểm, phụ phí và cảnh báo bẫy lãi suất phẳng (Flat-rate) theo Thông tư 43/2016/TT-NHNN.",
    "domain": "vietnam-life",
    "subdomain": "tax",
    "category": "office",
    "route": "#/tools/loan-apr-calculator-vn",
    "status": "active",
    "processing": "browser",
    "tags": [
      "lãi suất",
      "loan",
      "apr",
      "ear",
      "trả góp",
      "lãi phẳng",
      "flat rate",
      "vay tiêu dùng",
      "irr",
      "vietnam life",
      "việt nam"
    ]
  },
  {
    "id": "social-insurance-calculator-vn",
    "name": "Tính BHXH - BHYT - BHTN",
    "description": "Tính bảo hiểm bắt buộc người lao động và người sử dụng lao động. Tự động áp dụng mức lương cơ sở theo mốc 01/07/2026 và mức trần bảo hiểm thất nghiệp theo 4 vùng (NĐ 293/2025).",
    "domain": "vietnam-life",
    "subdomain": "insurance",
    "category": "office",
    "route": "#/tools/social-insurance-calculator-vn",
    "status": "active",
    "processing": "browser",
    "tags": [
      "bhxh",
      "bhyt",
      "bhtn",
      "bảo hiểm xã hội",
      "lương cơ sở",
      "trần bảo hiểm",
      "vùng lương",
      "vietnam life",
      "việt nam"
    ]
  },
  {
    "id": "electricity-calculator-vn",
    "name": "Tính Tiền Điện Sinh Hoạt",
    "description": "Tính tiền điện bậc thang sinh hoạt theo biểu giá 6 bậc mới nhất (QĐ 1279/QĐ-BCT) của EVN. Hỗ trợ tính số ngày lẻ theo chu kỳ ghi chỉ số và tách bạch rõ thuế suất VAT.",
    "domain": "vietnam-life",
    "subdomain": "housing",
    "category": "utils",
    "route": "#/tools/electricity-calculator-vn",
    "status": "active",
    "processing": "browser",
    "tags": [
      "tiền điện",
      "điện sinh hoạt",
      "evn",
      "bậc thang",
      "hóa đơn điện",
      "electricity",
      "qđ 1279",
      "vietnam life",
      "việt nam"
    ]
  }
];

export default TOOLIO_SNAPSHOT;
